FROM golang:1.19.3

# Source:   https://github.com/rubenv/sql-migrate
# Docs:     https://pkg.go.dev/github.com/rubenv/sql-migrate#section-readme
RUN go install github.com/rubenv/sql-migrate/...@latest
